# Generated by Django 2.2.6 on 2019-11-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191120_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Ваше имя:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exp',
            field=models.CharField(choices=[('До года', 'До года'), ('От года до трёх лет', 'От года до трёх лет'), ('Больше трех лет', 'Больше трех лет')], default='До года', max_length=30, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(choices=[('Актер', 'Актер'), ('Режиссер', 'Режиссер'), ('Оператор', 'Оператор'), ('Монтажер', 'Монтажер')], default='Актер', max_length=30, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.CharField(default='.../час работы', max_length=15, verbose_name='Цена'),
        ),
    ]
