# Generated by Django 2.2.6 on 2019-11-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191121_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acess',
            field=models.CharField(choices=[('Разрешить просмотр', 'allowed'), ('Не разрешать', 'not_allowed')], default='not_allowed', max_length=30, verbose_name='Доступ'),
        ),
    ]
