# Generated by Django 2.2.6 on 2019-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191128_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acess',
            field=models.CharField(choices=[('not_allowed', 'not_allowed'), ('allowed', 'allowed')], default='Не разрешать', max_length=30, verbose_name='Доступ'),
        ),
    ]
